name: 'Wasp Deploy'
description: 'Deploy with Wasp to Fly.io'
inputs:
  fly-token: 
    description: 'Fly.io API token'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Install Wasp
      shell: bash
      run: curl -sSL https://get.wasp.sh/installer.sh | sh -s -- -v 0.16.0
    - name: Install Flyctl
      uses: superfly/flyctl-actions/setup-flyctl@master
    - name: Deploy
      run: wasp deploy fly deploy
      shell: bash
      env:
        FLY_API_TOKEN: ${{ inputs.fly-token }}
